# Generated by Django 5.0.6 on 2024-07-31 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='address_line_1',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='street',
            field=models.CharField(default='not provided', max_length=255),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='zip_code',
            field=models.CharField(default='not provided', max_length=20),
        ),
    ]
