# Generated by Django 5.0.6 on 2024-08-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_orders_id_orders_created_at_orders_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
