# Generated by Django 5.0.6 on 2024-08-04 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_deliveryaddress_created_at_and_more'),
    ]

    operations = [
    ]
