# Generated by Django 5.0.6 on 2024-08-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_handle_duplicate_uids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='orders',
        ),
    ]
