# Generated by Django 5.0.6 on 2024-08-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Order Placed', max_length=50),
        ),
    ]
