# Generated by Django 5.0.6 on 2024-08-09 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_paymentmethod_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='details',
        ),
    ]
