# Generated by Django 5.0.6 on 2024-08-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_paymentmethod_upi_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
