# Generated by Django 5.0.6 on 2024-08-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='method',
            field=models.CharField(choices=[('credit_card', 'Credit or Debit Card'), ('net_banking', 'Net Banking'), ('upi', 'UPI'), ('emi', 'EMI'), ('cod', 'Cash on Delivery')], default='Cash on Delivery', max_length=20),
        ),
    ]
