# Generated by Django 5.0.6 on 2024-08-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_profile_email_profile_mobile_phone_profile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile'),
        ),
    ]
