# Generated by Django 5.0.6 on 2024-07-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(upload_to='static/category'),
        ),
        migrations.AlterField(
            model_name='productsimage',
            name='image',
            field=models.ImageField(upload_to='static/product'),
        ),
    ]
