# Generated by Django 5.0.6 on 2024-08-10 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

   
