# Generated by Django 5.0.6 on 2024-08-15 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delivery_date',
        ),
    ]
